### ISSUE TITLE
Espen Rosenquist would like to be added as an editor to this repo

### ISSUE THREAD

**Issue by rasundsbak** [uio-carpentry/2022-11-22-uio#1]
from email conversation:
...I have just started to look at lesson material. I will clone the repo and work locally, but I do not have permissions to change the repo directly (probably because I am not employed by UiO?). If someone could grant me the rights it would be nice, otherwise I will send pull requests.

answer to: "Espen Rosenquist" <espen.rosenquist@gmail.com>

**Comment by arockenberger** [comment]
I have send @Espen an invite! @Rasundsbak you should have writing access now, yes?

**Comment by espen** [comment]
@arockenberger this is not the Espen you are looking for.

**Comment by arockenberger** [comment]
Oh, sorry! Please ignore :)
